openapi: "3.0.3"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1

components:
  responses:
    name:
      description: "sadf"
      content:
        application/json:
          schema: {}

paths:
  /test:
    get:
      responses:
        "200":
          description: OK
